#!/bin/bash
# Setup script for GitHub Pages deployment

echo "=== 3D Printing App Privacy Policy - GitHub Setup ==="
echo ""
echo "Run these commands from YOUR local terminal (not this one):"
echo ""
echo "# 1. Download this folder to your local machine"
echo "# 2. Navigate to the folder"
echo "cd 3d-printing-app-privacy"
echo ""
echo "# 3. Initialize git (if not already done)"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit: Add privacy policy'"
echo ""
echo "# 4. Create GitHub repo and push (try redheadvault first, then redhead if that fails)"
echo ""
echo "Option A - If username is 'redheadvault':"
echo "gh repo create redheadvault/3d-printing-app-privacy --public --source=. --push"
echo ""
echo "OR manually:"
echo "git remote add origin git@github.com:redheadvault/3d-printing-app-privacy.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Option B - If username is 'redhead':"
echo "gh repo create redhead/3d-printing-app-privacy --public --source=. --push"
echo ""
echo "OR manually:"
echo "git remote add origin git@github.com:redhead/3d-printing-app-privacy.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# 5. Enable GitHub Pages"
echo "Go to: https://github.com/YOUR-USERNAME/3d-printing-app-privacy/settings/pages"
echo "Set Source to 'Deploy from a branch'"
echo "Set Branch to 'main' and folder to '/ (root)'"
echo "Click Save"
echo ""
echo "# 6. Your privacy policy will be live at:"
echo "https://YOUR-USERNAME.github.io/3d-printing-app-privacy/"
echo ""
echo "Use that URL in App Store Connect!"
